#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0
management:
  endpoints:
    web:
      exposure:
        include:
          - "prometheus"
          - "health"
          - "info"
